COEFFICIENT_LIMIT = 14

POINT_NULL = b'\x00'
POINT_INT = b'\x01'
POINT_FLOAT = b'\x02'

LIST_METRICS = b'\x01'
LIST_BUCKETS = b'\x03'
STREAM_MODE = b'\x04'
PAYLOAD = b'\x05'
FLUSH = b'\x06'

# Payload sizes bytes
TCP_SS = 4
BUCKETS_SS = 8
BUCKET_SS = 2
METRICS_SS = 8
METRIC_SS = 2
TIME_SIZE = 8

PACK_FMT = {1: ">B", 2: ">H", 4: ">L", 8: ">Q"}
